entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: noreply@youcanhack.me
      storage: /acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: false

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true